version: '3'
services:
  redis-docker:
    image: redis:latest
    platform: linux/amd64
    container_name: 'insight-redis'
    command: redis-server --port 6379
    ports:
      - '6379:6379'
    volumes:
      - ./docker/data/redis:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysql-docker:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: 'insight'
      MYSQL_ROOT_PASSWORD: '1234'
      TZ: Asia/Seoul
    container_name: 'insight-mysql'
    ports:
      - '3306:3306'
    volumes:
      - insight_mysql_data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
volumes:
  insight_mysql_data: